import * as SiIcons from 'react-icons/si';
import { FaCloud, FaDatabase, FaQuestionCircle } from 'react-icons/fa';

// Dynamic logo import
const logoModules = import.meta.glob('../logos/*.{png,jpg,jpeg,webp,svg,avif}', { eager: true });

// Create a map of logo filenames to their paths
const logoPathMap = {};
Object.keys(logoModules).forEach(path => {
  const filename = path.split('/').pop();
  logoPathMap[filename.toLowerCase()] = logoModules[path].default;
});

// Debug logging

// Logo mapping - maps technology names to logo filenames
export const getLogoPath = (techName) => {
  if (!techName) return null;
  
  const normalized = techName.toLowerCase().trim();
  
  // AI/ML Concepts - prioritize these logos over robot icon
  const aimlConceptLogos = {
    "ai": "AI.png",
    "ai/ml": "AIML.png",
    "artificial intelligence": "AI.png",
    "machine learning": "Machine Learning.png",
    "deep learning": "Machine Learning.png",
    "nlp": "NLP.png",
    "natural language processing": "NLP.png",
    "computer vision": "Machine Learning.png",
    "gen ai": "Generative AI.png",
    "genai": "Generative AI.png",
    "generative ai": "Generative AI.png",
    "llm": "LLM.png",
    "large language model": "Large Language Models.png",
    "foundation models": "Large Language Models.png",
    "rag": "RAG.png",
    "transfer learning": "Transfer Learning.png",
    "transformers": "Transformers.png",
    "inference engine": "Inference Engine.png",
    "model serving": "Model Serving.png",
    "model inference": "Model Inference.png",
    "feature store": "Feature Store.png",
    "explainable ai": "Explainable AI.png",
    "aiml": "AIML.png",
    "model training": "Model Training.png",
  };
  
  // Check AI/ML concepts first
  if (aimlConceptLogos[normalized]) {
    const logoFile = aimlConceptLogos[normalized].toLowerCase();
    if (logoPathMap[logoFile]) {
      return logoPathMap[logoFile];
    } else {
    }
  }
  
  const logoMap = {
    // AWS Services
    "aws": "AWS.png",
    "amazon aws": "AWS.png",
    "amazon": "AWS.png",
    "amazon web services": "AWS.png",
    "aws lambda": "AWS Lambda.png",
    "aws sagemaker": "AWS SageMaker.webp",
    "aws rds": "AWS RDS.png",
    "aws ebs": "AWS EBS.png",
    "aws efs": "AWS EFS.png",
    "amazon dynamodb": "Amazon DynamoDB.png",
    "dynamodb": "Amazon DynamoDB.png",
    "amazon rds": "Amazon RDS.png",
    "rds": "Amazon RDS.png",
    "amazon aurora": "Amazon Aurora.png",
    "aurora": "Amazon Aurora.png",
    "amazon s3": "Amazon S3.png",
    "s3": "Amazon S3.png",
    "amazon ec2": "Amazon EC2.png",
    "ec2": "Amazon EC2.png",
    "amazon ecs": "Amazon ECS.png",
    "ecs": "Amazon ECS.png",
    "amazon eks": "Amazon EKS.png",
    "eks": "Amazon EKS.png",
    "amazon efs": "Amazon Elastic File System.png",
    "amazon elasticache": "Amazon ElastiCache.png",
    "elasticache": "Amazon ElastiCache.png",
    "amazon cloudfront": "Amazon CloudFront.png",
    "cloudfront": "Amazon CloudFront.png",
    "amazon bedrock": "Amazon Bedrock.webp",
    "bedrock": "Amazon Bedrock.webp",
    "amazon q": "Amazon Q.png",
    "amazon redshift": "Amazon Redshift.png",
    "redshift": "Amazon Redshift.png",
    "amazon documentdb": "Amazon DocumentDB.jpg",
    "documentdb": "Amazon DocumentDB.jpg",
    "amazon opensearch": "Amazon OpenSearch.webp",
    "opensearch": "Amazon OpenSearch.webp",
    "amazon vpc": "Amazon VPC.png",
    "vpc": "Amazon VPC.png",
    "aws aurora postgresql": "Amazon Aurora.png",
    "aws aurora": "Amazon Aurora.png",
    "aws aurora oracle": "Amazon Aurora.png",
    
    // Azure Services
    "azure": "Azure.png",
    "microsoft azure": "Microsoft Azure.png",
    "azure sql": "Azure SQL.png",
    "azure sql database": "Azure SQL.png",
    "azure cosmos db": "Azure Cosmos DB.png",
    "cosmos db": "Azure Cosmos DB.png",
    "azure openai": "Azure OpenAI.png",
    "azure functions": "Azure Functions.png",
    "azure app service": "Azure App Service.png",
    "azure devops": "Azure DevOps.png",
    "azure machine learning": "Azure Machine Learning.webp",
    "azure vm": "Azure VM.png",
    "azure data lake storage": "Azure Data Lake Storage.png",
    "azure synapse analytics": "Azure Synapse Analytics.png",
    "azure cognitive services": "Azure Cognitive Services.png",
    "azure kubernetes service": "Microsoft Azure Kubernetes Service.png",
    "aks": "Microsoft Azure Kubernetes Service.png",
    "microsoft fabric": "Microsoft Fabric.png",
    
    // GCP Services
    "gcp": "GCP.png",
    "google cloud platform": "GCP.png",
    "google cloud": "Google Cloud.png",
    "google cloud sql": "Google Cloud SQL.png",
    "cloud sql": "GCP SQL.png",
    "gcp sql": "GCP SQL.png",
    "google cloud spanner": "Google Cloud Spanner.png",
    "google firestore": "Firestore.png",
    "firestore": "Firestore.png",
    "google kubernetes engine": "Google Cloud.png",
    "gke": "Google Cloud.png",
    "google cloud storage": "Google Cloud Storage.png",
    "google bigquery": "Google BigQuery.png",
    "bigquery": "Google BigQuery.png",
    "google bigtable": "Google Bigtable.png",
    "google cloud run": "Google Cloud Run.png",
    "google gemini": "Google Gemini.png",
    "gemini": "Google Gemini.png",
    "google ai": "Google AI.png",
    "google": "Google.png",
    "firebase": "Firebase.png",
    
    // Databases
    "mongodb": "MongoDB.png",
    "mongo db": "MongoDB.png",
    "mysql": "MySQL.png",
    "postgresql": "PostgreSQL.png",
    "postgres": "PostgreSQL.png",
    "postgis": "PostGIS.png",
    "mariadb": "MariaDB.png",
    "oracle database": "Oracle Database.png",
    "oracle": "Oracle.png",
    "oracle autonomous database": "Oracle Autonomous Database.png",
    "oracle cloud": "Oracle Cloud.png",
    "oracle cx": "Oracle CX.png",
    "oracle crm": "Oracle CRM.png",
    "ibm db2": "IBM Db2.png",
    "db2": "IBM Db2.png",
    "snowflake": "Snowflake.png",
    "redis": "Redis.png",
    "elasticsearch": "Elastic Search.png",
    "kafka": "Apache Kafka.png",
    "cassandra": "Apache Cassandra.png",
    "couchbase": "Couchbase.png",
    "neo4j": "Neo4j.png",
    "clickhouse": "ClickHouse.png",
    "teradata": "Teradata.png",
    "teradata vantage": "Teradata Vantage.png",
    "timescaledb": "TimescaleDB.png",
    "marklogic": "MarkLogic.png",
    "bson": "BSON.png",
    "key-value database": "Redis.png",
    "in-memory database": "Redis.png",
    "managed database services": "Database.webp",
    
    // AI/ML Models & Platforms
    "openai": "OpenAI.png",
    "chatgpt": "ChatGPT.png",
    "gpt-4": "ChatGPT.png",
    "gpt-5": "ChatGPT.png",
    "whisper": "Whisper.png",
    "claude": "Claude.png",
    "anthropic": "Anthropic.png",
    "cohere": "Cohere.png",
    "mistral": "Mistral AI.png",
    "mistral ai": "Mistral AI.png",
    "deepseek": "DeepSeek.png",
    "grok": "Grok.png",
    "meta ai": "Meta AI.png",
    "meta llama": "Meta Llama 3.png",
    "llama": "Meta Llama 3.png",
    "perplexity ai": "Perplexity AI.png",
    "hugging face": "Hugging Face.png",
    "H2O.ai": "h2o.png",
    "h2o": "h2o.png",
    "replicate": "Replicate.png",
    "pytorch": "PyTorch.png",
    "pytorch lightning": "PyTorch Lightning.png",
    "tensorflow": "TensorFlow.png",
    "keras": "Keras.png",
    "jax": "JAX.avif",
    "scikit-learn": "Scikit-learn.png",
    "xgboost": "XGBoost.png",
    "onnx": "ONNX.png",
    "mlflow": "mlflow.png",
    "ML flow": "mlflow.png",
    "prefect": "Prefect.svg",
    "airflow": "Apache Airflow.png",
    "kubeflow": "Kubeflow.png",
    "datarobot": "DataRobot.webp",
    "watsonx": "watsonx.jpg",
    "ibm watson": "IBM Watson Machine Learning.png",
    "ibm watson machine learning": "IBM Watson Machine Learning.png",
    "langchain": "LangChain.png",
    "llamaindex": "LlamaIndex.svg",
    "chroma": "chroma1.png",
    "milvus": "Milvus.png",
    "pinecone": "Pinecone.webp",
    "weaviate": "Weaviate.webp",
    "qdrant": "Qdrant.png",
    "vectara": "Vectara.png",
    "jasper ai": "Jasper AI.png",
    "midjourney": "Mid Journey.png",
    "mid journey": "Mid Journey.png",
    "stable diffusion": "Stable Diffusion.png",
    "alphafold": "AlphaFold.png",
    "notion ai": "Notion AI.png",
    "copilot": "Copilot.png",
    "microsoft copilot": "Microsoft Copilot.png",
    "github copilot": "Copilot.png",
    "fastai": "Fastai.png",
    "Adobe Sensei": "Adobe Sensei AI.png",
    "adobe sensei ai": "Adobe Sensei AI.png",
    "adobe sensei ai cloud platform": "Adobe Sensei AI.png",
    "adobe": "Adobe.png",
    "leena ai": "Leena AI.png",
    "salesforce einstein": "Salesforce Einstein.png",
    "sap ai": "SAP AI.png",
    "splunk ai": "Splunk AI.webp",
    "servicenow ai": "ServiceNow AI.png",
    "cisco ai": "Cisco AI.png",
    "microsoft fabric": "Microsoft Fabric.png",
    
    // CRM Systems
    "salesforce": "Salesforce.png",
    "salesforce crm": "Salesforce.png",
    "salesforce einstein": "Salesforce Einstein.png",
    "salesforce lightning": "Salesforce Lightning.png",
    "hubspot": "HubSpot.png",
    "hubspot crm": "HubSpot.png",
    "zoho": "Zoho.png",
    "zoho crm": "Zoho CRM.png",
    "zoho desk": "Zoho Desk.png",
    "zoho one": "Zoho One.png",
    "pipedrive": "Pipedrive.png",
    "netsuite crm": "NetSuite CRM.png",
    "servicenow": "ServiceNow.png",
    "servicenow ai": "ServiceNow AI.png",
    "dynamics 365": "Microsoft Dynamics 365.webp",
    "microsoft dynamics 365": "Microsoft Dynamics 365.webp",
    "dynamics crm": "Microsoft Dynamics 365.webp",
    "microsoft dynamics crm": "Microsoft Dynamics 365.webp",
    "sap crm": "SAP CRM.webp",
    "sap sales cloud": "SAP Sales Cloud.webp",
    "sap customer experience": "SAP Customer Experience.webp",
    "veeva crm": "Veeva CRM.png",
    "peoplesoft crm": "PeopleSoft CRM.png",
    "sage crm": "Sage CRM.png",
    "sprinklr": "Sprinklr.png",
    "copper": "Copper.png",
    "creatio": "Creatio.png",
    "crmnext": "CRMNext.png",
    "leadsquared": "LeadSquared.png",
    "nimble crm": "Nimble CRM.png",
    "SuiteCRM": "SuiteCRM.png",
    "suite crm": "SuiteCRM.png",
    "workday": "Workday.jpg",
    "whatsapp crm": "Whatsapp CRM.png",
    "real estate crm": "Real Estate CRM.png",
    "healthcare crm": "Healthcare CRM.png",
    "customer engagement platform": "Customer Engagement Platform.png",
    "open source crm": "Open Source CRM.png",
    "on-premise crm": "On-Premise CRM.png",
    "unified customer view": "Unified Customer View.png",
    
    // Cloud Platforms
    "ibm cloud": "IBM Cloud.png",
    "ibm": "IBM.png",
    "digitalocean": "DigitalOcean.png",
    "linode": "Linode.png",
    "vultr": "Vultr.svg",
    "heroku": "Heroku.png",
    "heroku dynos": "Heroku.png",
    "heroku postgres": "Heroku Postgres.png",
    "coreweave": "CoreWeave.png",
    "vmware": "VMware.png",
    "vmware vsphere": "VMware vSphere.jpg",
    "vmware vcloud": "VMware vCloud.jpg",
    "nutanix": "Nutanix.png",
    "openstack": "OpenStack.svg",
    "openshift": "openshift.png",
    "red hat openshift": "openshift.png",
    "red hat": "Red Hat.png",
    "redhat": "Red Hat.png",
    "alibaba cloud": "Alibaba Cloud.png",
    "rackspace cloud": "Rackspace Cloud.jpg",
    "akamai": "Akamai.png",
    "cloudflare": "Cloudflare.png",
    "cloudflare workers": "Cloudflare Workers.png",
    "cloudflare cdn": "Cloudflare CDN.png",
    "Hyperconverged Infrastructure": "Hyperconverged Infrastructure.jpg",
    "hci": "Hyperconverged Infrastructure.jpg",
    "gpu cloud": "GPU Cloud.png",
    "edge computing": "Edge Computing.png",
    "Virtual Private Cloud": "Virtual Private Cloud.webp",
    "vpc": "Virtual Private Cloud.webp",
    "itar": "ITAR.png",
    "fedramp": "FedRAMP.webp",
    "government cloud": "Government Cloud.png",
    "ai cloud platform": "AI Cloud Platform.png",
    "ai infrastructure": "AI Infrastructure.png",
    "ai orchestration": "AI Orchestration.png",
    
    // Infrastructure & DevOps
    "docker": "Docker.png",
    "kubernetes": "Kubernetes.png",
    "jenkins": "Jenkins.png",
    "git": "Git.png",
    "github": "GitHub.png",
    "gitlab": "GitLab.png",
    "terraform": "Terraform.png",
    "nginx": "Nginx.png",
    "apache": "Apache.svg",
    "linux": "Linux.png",
    "windows": "Windows.png",
    "sql server": "SQL Server.png",
    "mssql": "SQL Server.png",
    "ms sql": "SQL Server.png",
    "t-sql": "SQL Server.png",
    "dax": "DAX.png",
    "ml ops": "ML Ops.png",
    "mlops": "ML Ops.png",
    "model serving": "Model Serving.png",
    "inference engine": "Inference Engine.png",
    "model inference": "Model Inference.png",
    "feature store": "Feature Store.png",
    "nvidia hgx": "Nvidia HGX.png",
    
    // Analytics & BI
    "tableau": "Tableau.png",
    "sap analytics": "SAP AI.webp",
    "sap ai": "SAP AI.webp",
    "splunk": "Splunk AI.webp",
    "splunk ai": "Splunk AI.webp",
    "databricks": "Databricks.png",
    "apache spark": "Apache Spark.png",
    "spark": "Apache Spark.png",
    "apache hadoop": "Apache Hadoop.png",
    "hadoop": "Apache Hadoop.png",
    "apache hive": "Apache Hive.webp",
    "hive": "Apache Hive.webp",
    "apache mxnet": "Apache MXNet.png",
    "mxnet": "Apache MXNet.png",
    "application platform": "Application Platform.png",
    "Data Warehouse": "Data Warehouse.webp",
    "large language models": "Large Language Models.png",
    "nlp": "NLP.png",
    "rag": "RAG.png",
    "transformers": "Transformers.png",
    "inference engine": "Inference Engine.png",
    "model serving": "Model Serving.png",
    "model inference": "Model Inference.png",
    "feature store": "Feature Store.png",
    "explainable ai": "Explainable AI.png",
    "transfer learning": "Transfer Learning.png",
    "generative ai": "Generative AI.png",
    "machine learning": "Machine Learning.png",
    
    // Additional CRM Systems
    "aeon crm": "Aeon CRM.png",
    "agile crm": "Agile CRM.jpg",
    "aim crm": "AIM CRM.png",
    "backstop crm": "Backstop CRM.jpg",
    "basix crm": "BASIX CRM.jpg",
    "bespoke crm": "Bespoke CRM.avif",
    "bigin crm": "Bigin CRM.png",
    "bitrix24 crm": "Bitrix24 CRM.jpg",
    "bloomtools crm": "Bloomtools CRM.jpg",
    "brevo crm": "Brevo CRM.png",
    "brokadesk mt4 crm": "Brokadesk MT4 CRM.png",
    "converse crm": "Converse CRM.webp",
    "daxrm crm": "DAXRM CRM.png",
    "dealersocket crm": "DealerSocket CRM.png",
    "ecollat crm": "Ecollat CRM.png",
    "engagebay": "Engagebay.png",
    "ensivo crm": "Ensivo CRM.jpg",
    "ezee crm": "Ezee CRM.png",
    "focus crm": "Focus CRM.png",
    "freshworks crm": "Freshworks CRM.png",
    "got sales crm": "Got Sales CRM.png",
    "insightly crm": "Insightly CRM.png",
    "intuit crm": "Intuit CRM.jpg",
    "jetpack crm": "Jetpack CRM.svg",
    "kapture crm": "Kapture CRM.jpg",
    "leadsquared sales crm": "LeadSquared Sales CRM.avif",
    "lozics crm": "LOZICS CRM.png",
    "magenta crm": "Magenta CRM.png",
    "monday.com crm": "monday.com CRM.png",
    "myflow": "Myflow.png",
    "odoo crm": "Odoo CRM.png",
    "panda crm": "Panda CRM.svg",
    "poco crm": "POCO CRM.png",
    "scale crm": "SCALE CRM.png",
    "sugar crm": "Sugar CRM.webp",
    "tableau crm": "Tableau CRM.png",
    "vtiger crm": "Vtiger CRM.jpg",
    "zendesk crm": "Zendesk CRM.webp",
    
    // Additional Cloud & Infrastructure
    "e2e networks": "E2E Networks.png",
    "exabytes": "Exabytes.png",
    "hetzner": "Hetzner.png",
    "inap": "INAP.png",
    "ionos": "IONOS.png",
    "kt cloud": "KT Cloud.png",
    "leaseweb": "Leaseweb.jpg",
    "liquid web": "Liquid Web.png",
    "lumen": "Lumen.png",
    "lyve": "Lyve.png",
    "open telekom": "Open Telekom.png",
    "ovh cloud": "OVH Cloud.png",
    "rackcorp secure": "RackCorp Secure.png",
    "sciex cloud": "Sciex Cloud.png",
    "shinjiru": "Shinjiru.png",
    "sitehost": "SiteHost.jpg",
    "statushub": "StatusHub.jpg",
    "tm one cloud alpha": "TM One Cloud Alpha.png",
    "tencent": "Tencent.avif",
    "huawei": "Huawei.png",
    "aruba": "Aruba.jpg",
    "cisco": "Cisco.png",
    "nexon": "Nexon.svg",
    "iseek": "iseek.png",
    "iver": "Iver.png",
    "hotjar": "Hotjar.png",
    "cursor ai": "Cursor AI.avif",
    
    // Additional AI/ML & Data
    "neural networks": "Neural Networks.png",
    "predictive analytics": "Predictive Analytics.png",
    "graph database": "Graph Database.png",
    "key value database": "Key Value Database.png",
    "key-value database": "Key-Value Database.png",
    "nosql database": "NoSQL Database.png",
    "sqlite": "SQLite.jpg",
    "sybase": "Sybase.png",
    "maxdb": "MaxDB.jpg",
    "ravendb": "RavenDB.png",
    "data foundry": "Data Foundry.png",
    "app platform": "App Platform.png",
    "enterprise ai": "Enterprise AI.png",
    "on-premise": "On-Premise.png",
    "on premise": "On-Premise.png",
    "cmc": "CMC.png",
    "ml": "ML.png",
    "perplexity": "Perplexity.png",
    "perplexity ai": "Perplexity AI.png",
    "clara": "Clara.png",
    "triblio": "Triblio.png",
    "mailchimp": "MailChimp.png",
    "odoo": "Odoo.png",
    "zendesk": "Zendesk.webp",
    "whatsapp crm": "Whatsapp CRM.webp",
    "real estate crm": "Real Estate CRM.png",
    "healthcare crm": "Healthcare CRM.png",
    "customer engagement platform": "Customer Engagement Platform.png",
    "open source crm": "Open Source CRM.png",
    "on-premise crm": "On-Premise CRM.png",
    "unified customer view": "Unified Customer View.png",
    "ais": "AIS.png",
    "ais business": "AIS Business.png",
    "ai cloud platform": "AI Cloud Platform.png",
    "ai infrastructure": "AI Infrastructure.png",
    "ai orchestration": "AI Orchestration.png",
    "bson": "BSON.png",
    "cassandra": "Cassandra.png",
    "clara": "Clara.png",
    "cosmos bd": "Cosmos BD.png",
    "couchbase": "Couchbase.png",
    "creatio": "Creatio.png",
    "crmnext": "CRMNext.png",
    "leadsquared": "LeadSquared.png",
    "nimble crm": "Nimble CRM.png",
    "suitcrm": "Suitecrm.png",
    "suite crm": "Suitecrm.png",
    "workday": "Workday.jpg",
    "influxdb": "InfluxDB.svg",
    "in-memory database": "In-Memory Database.png",
    "managed database services": "Managed Database Services.png",
    "vector database": "Vector Database.avif",
    "opencv": "OpenCV.webp",
    "nvidia hgx": "Nvidia HGX.png",
    "nvidia": "Nvidia.png",
    "timescaledb": "TimescaleDB.png",
    "triblio": "Triblio.png",
    "veeva crm": "Veeva CRM.png",
    "virtual private cloud": "Virtual Private Cloud.webp",
    "vmware vsphere": "VMware vSphere.jpg",
    "vmware vcloud": "VMware vCloud.jpg",
    "vmware": "VMware.png",
    "watsonx": "watsonx.jpg",
    "xgboost": "XGBoost.png",
    
    // Generic/Fallback
    "database": "Database.webp",
    "cloud": "Cloud.webp",
    "cloud computing": "Cloud.webp",
    "crm": "CRM.png",
    "on prem": "Database.png",
    "on-prem": "Database.png",
    "not detected": null,

    // MDM / UEM / Endpoint Management
    "42gears suremdm": "42Gears SureMDM.png",
    "suremdm": "42Gears SureMDM.png",
    "addigy": "Addigy.png",
    "addigy (apple mdm)": "Addigy (Apple MDM).png",
    "airdroid business": "AirDroid Business.png",
    "airdroid business mdm": "AirDroid Business MDM.png",
    "airwatch": "AirWatch (legacy keyword).png",
    "applivery": "Applivery.png",
    "applivery uem": "Applivery UEM.png",
    "blackberry uem": "BlackBerry UEM.png",
    "chrome enterprise management": "Chrome Enterprise Management.png",
    "chromebooks": "Chromebooks.png",
    "chromeos": "ChromeOS.png",
    "esper": "Esper.png",
    "esper device management": "Esper Device Management.png",
    "google endpoint management": "Google Endpoint Management.png",
    "hexnode uem": "Hexnode UEM.png",
    "hexnode": "Hexnode UEM.png",
    "ibm maas360": "IBM MaaS360.png",
    "ivanti neurons for uem": "Ivanti Neurons for UEM.png",
    "ivanti": "Ivanti Neurons for UEM.png",
    "jamf pro": "Jamf Pro.png",
    "jamf now": "Jamf Now.png",
    "jamf business": "Jamf Business.png",
    "jamf": "Jamf Pro.png",
    "jumpcloud": "JumpCloud.png",
    "jumpcloud device management": "JumpCloud Device Management.png",
    "kandji": "Kandji.png",
    "kandji (apple-focused uem)": "Kandji (Apple-focused UEM).png",
    "manageengine mdm": "ManageEngine MDM.png",
    "manageengine mobile device manager plus": "ManageEngine Mobile Device Manager Plus.png",
    "manageengine": "ManageEngine MDM.png",
    "microsoft intune": "Microsoft Intune.png",
    "intune": "Microsoft Intune.png",
    "miradore mdm": "Miradore MDM.png",
    "miradore": "Miradore MDM.png",
    "mobile device management": "Mobile Device Management (MDM).png",
    "mdm": "Mobile Device Management (MDM).png",
    "ninjarmm": "NinjaOne.png",
    "ninjaone": "NinjaOne.png",
    "ninjaone endpoint management": "NinjaOne Endpoint Management.png",
    "simplemdm": "SimpleMDM.png",
    "scalefusion": "Scalefusion MDM.png",
    "scalefusion mdm": "Scalefusion MDM.png",
    "scalefusion (promobi)": "Scalefusion (ProMobi).png",
    "soti mobicontrol": "SOTI MobiControl.png",
    "soti": "SOTI MobiControl.png",
    "vmware workspace one": "VMware Workspace ONE.png",
    "vmware workspace one uem": "VMware Workspace ONE UEM.png",
    "workspace one": "VMware Workspace ONE.png",

    // Backup & Data Protection
    "acronis cyber protect": "Acronis Cyber Protect.png",
    "acronis": "Acronis Cyber Protect.png",
    "arcserve udp": "Arcserve UDP.png",
    "arcserve": "Arcserve UDP.png",
    "avamar": "Avamar.png",
    "emc avamar": "EMC Avamar.png",
    "backup & data protection vendors": "Backup & Data Protection Vendors.png",
    "barracuda backup": "Barracuda Backup.png",
    "barracuda": "Barracuda Backup.png",
    "cohesity": "Cohesity.png",
    "cohesity dataprotect": "Cohesity DataProtect.png",
    "commvault": "Commvault.png",
    "commvault cloud": "Commvault Cloud.png",
    "datto backup": "Datto Backup.png",
    "datto": "Datto Backup.png",
    "dell emc data domain": "Dell EMC Data Domain.png",
    "dell emc networker": "Dell EMC NetWorker.png",
    "dell networker": "Dell NetWorker.png",
    "dell powerprotect data manager": "Dell PowerProtect Data Manager.png",
    "druva data resiliency cloud": "Druva Data Resiliency Cloud.png",
    "druva": "Druva Data Resiliency Cloud.png",
    "emc networker": "EMC Networker.png",
    "hycu": "HYCU.png",
    "ibm spectrum protect": "IBM Spectrum Protect.png",
    "ibm storage protect": "IBM Storage Protect.png",
    "ibm tivoli storage management": "IBM Tivoli Storage Management.png",
    "tivoli storage manager": "Tivoli Storage Manager.png",
    "msp360 backup": "MSP360 Backup.png",
    "msp360": "MSP360 Backup.png",
    "nakivo backup & replication": "NAKIVO Backup & Replication.png",
    "nakivo": "NAKIVO Backup & Replication.png",
    "netapp bluexp": "NetApp BlueXP.png",
    "netapp": "NetApp BlueXP.png",
    "rubrik": "Rubrik.png",
    "rubrik security cloud": "Rubrik Security Cloud.png",
    "unitrends backup": "Unitrends Backup.png",
    "unitrends": "Unitrends Backup.png",
    "veeam": "Veeam.png",
    "veeam backup & replication": "Veeam Backup & Replication.png",
    "veritas": "Veritas.jpg",
    "veritas netbackup": "Veritas NetBackup.png",
    "zerto": "Zerto.png",
    "pure storage platform": "Pure Storage Platform.png",
    "pure storage": "Pure Storage Platform.png",

    // Telecom / Mobile Operators
    "at&t": "AT&T.png",
    "at&t mobility": "AT&T Mobility.png",
    "bell canada": "Bell Canada.png",
    "bharti airtel": "Bharti Airtel.png",
    "airtel": "Bharti Airtel.png",
    "bt": "BT.png",
    "bt global services": "BT Global Services.png",
    "china mobile": "China Mobile.png",
    "china telecom": "China Telecom.png",
    "china unicom": "China Unicom.png",
    "claro": "Claro (América Móvil).png",
    "comcast business mobile": "Comcast Business Mobile.png",
    "comcast": "Comcast Business Mobile.png",
    "deutsche telekom": "Deutsche Telekom.png",
    "ee (uk)": "EE (UK).png",
    "etisalat": "Etisalat (e&).png",
    "e&": "Etisalat (e&).png",
    "kddi": "KDDI.png",
    "kt corporation": "KT Corporation.png",
    "lg u+": "LG U+.png",
    "movistar": "Movistar.png",
    "mtn group": "MTN Group.png",
    "mtn": "MTN Group.png",
    "ntt docomo": "NTT Docomo.png",
    "ntt communications": "NTT Communications.png",
    "o2 telefonica": "O2 Telefónica.png",
    "o2": "O2 Telefónica.png",
    "optus business": "Optus Business.png",
    "optus": "Optus Business.png",
    "orange business": "Orange Business.png",
    "orange business services": "Orange Business Services.png",
    "reliance jio": "Reliance Jio.png",
    "jio": "Reliance Jio.png",
    "rogers communications": "Rogers Communications.png",
    "rogers": "Rogers Communications.png",
    "singtel": "Singtel.png",
    "singtel enterprise": "Singtel Enterprise.png",
    "sk telecom": "SK Telecom.png",
    "softbank telecom": "SoftBank Telecom.png",
    "softbank": "SoftBank Telecom.png",
    "spectrum mobile": "Spectrum Mobile.png",
    "starhub": "StarHub.png",
    "stc": "STC (Saudi Telecom).png",
    "stc (saudi telecom)": "STC (Saudi Telecom).png",
    "telefonica": "Telefonica.png",
    "telefonica tech": "Telefonica Tech.png",
    "telstra": "Telstra.png",
    "telstra enterprise": "Telstra Enterprise.png",
    "telus": "Telus.png",
    "telus mobility": "Telus Mobility.png",
    "tim brasil": "TIM Brasil.png",
    "t-mobile": "T-Mobile.png",
    "t-mobile us": "T-Mobile US.png",
    "t-systems": "T-Systems.png",
    "verizon": "Verizon.png",
    "verizon wireless": "Verizon Wireless.png",
    "vivo": "Vivo.png",
    "vodafone": "Vodafone.png",
    "vodafone business": "Vodafone Business.png",
    "vodafone global enterprise": "Vodafone Global Enterprise.png",
    "vodafone idea": "Vodafone Idea (Vi).png",

    // Hardware / Devices
    "advantech": "Advantech.png",
    "android": "Android.png",
    "apple": "Apple.png",
    "bluebird": "Bluebird.png",
    "bosch": "Bosch.png",
    "barcode scanners": "Barcode Scanners.png",
    "cat (caterpillar)": "CAT (Caterpillar).png",
    "cat phones": "CAT Phones (Caterpillar).png",
    "caterpillar": "CAT (Caterpillar).png",
    "chainway": "Chainway.png",
    "cipherlab": "CipherLab.png",
    "connected devices": "Connected Devices.png",
    "datalogic": "Datalogic.png",
    "dell": "Dell.png",
    "dell apex": "Dell APEX.png",
    "digital signage devices": "Digital Signage Devices.png",
    "edge devices": "edge devices.png",
    "enterprise smartphones": "Enterprise Smartphones.png",
    "esim": "eSIM.png",
    "field service devices": "Field Service Devices.png",
    "getac": "Getac.png",
    "handheld group": "Handheld Group.png",
    "healthcare mobility devices": "Healthcare Mobility Devices.png",
    "honeywell": "Honeywell.png",
    "hp": "HP.png",
    "hpe greenlake": "HPE GreenLake.png",
    "industrial printers": "Industrial Printers.png",
    "iot edge devices": "IoT Edge Devices.png",
    "ios": "IOS.png",
    "ipadOS": "iPadOS.png",
    "ipados": "iPadOS.png",
    "juniper": "Juniper.png",
    "juniper systems": "Juniper Systems.png",
    "kddi": "KDDI.png",
    "kyocera": "Kyocera.png",
    "label printers": "Label Printers.png",
    "laptops": "Laptops.png",
    "lenovo": "Lenovo.png",
    "lenovo xclarity": "Lenovo XClarity.png",
    "lenovo (motorola mobility)": "Lenovo (Motorola Mobility).png",
    "macos": "Macos.png",
    "meta": "Meta.png",
    "mfps": "MFPs.png",
    "microsoft surface": "Microsoft Surface.png",
    "microsoft (surface)": "Microsoft (Surface).png",
    "mobile computers": "Mobile Computers.png",
    "mobile printers": "Mobile Printers.png",
    "motorola mobility": "Motorola Mobility.png",
    "mpos": "mPOS.png",
    "mpos devices": "mPOS Devices.png",
    "network printers": "Network printers.png",
    "newland aidc": "Newland AIDC.png",
    "nfc": "NFC.png",
    "nfc payment devices": "NFC payment devices.png",
    "oppo": "Oppo.png",
    "panasonic": "Panasonic (Toughbook).png",
    "panasonic toughbook": "Panasonic Toughbook.png",
    "point mobile": "Point Mobile.png",
    "pos terminals": "POS Terminals.png",
    "receipt printers": "Receipt Printers.png",
    "rfid": "RFID (Radio Frequency Identification).png",
    "rfid readers": "RFID Readers.png",
    "rfid tags": "RFID tags.png",
    "rugged handheld computers": "Rugged Handheld Computers.png",
    "rugged smartphones": "Rugged Smartphones.png",
    "rugged tablets": "Rugged Tablets.png",
    "samsung": "Samsung.png",
    "schneider electric": "Schneider Electric.png",
    "self-service kiosks": "Self-service Kiosks.png",
    "sensors": "Sensors.png",
    "siemens": "Siemens.png",
    "smart glasses": "Smart Glasses.png",
    "smart meters": "smart meters.png",
    "smartphones": "Smartphones.png",
    "sonim technologies": "Sonim Technologies.png",
    "sonim": "Sonim Technologies.png",
    "tablets": "Tablets.png",
    "telematics devices": "Telematics Devices.png",
    "trimble": "Trimble.png",
    "unitech": "Unitech.png",
    "urovo technology": "Urovo Technology.png",
    "urovo": "Urovo Technology.png",
    "vehicle-mounted computers": "Vehicle-mounted Computers.png",
    "warehouse mobility devices": "Warehouse Mobility Devices.png",
    "wearables (enterprise)": "Wearables (Enterprise).png",
    "enterprise wearables": "Wearables (Enterprise).png",
    "xiaomi": "Xiaomi.png",
    "zebra": "Zebra.png",
    "zebra technologies": "Zebra Technologies.png",

    // Monitoring & Observability
    "datadog": "Datadog Infrastructure Monitoring.png",
    "datadog infrastructure monitoring": "Datadog Infrastructure Monitoring.png",
    "dynatrace": "Dynatrace.png",
    "logicmonitor": "LogicMonitor.png",
    "solarwinds hybrid cloud observability": "SolarWinds Hybrid Cloud Observability.png",
    "solarwinds": "SolarWinds Hybrid Cloud Observability.png",

    // Oracle extended
    "oracle ai": "Oracle AI.png",
    "oracle big data sql": "Oracle Big Data SQL.png",
    "oracle corporation database": "Oracle Corporation Database.png",
    "oracle cx cloud": "Oracle CX Cloud.png",
    "oracle netsuite crm": "Oracle NetSuite CRM.png",
    "oracle siebel crm": "Oracle Siebel CRM.png",
    "netsuite": "NetSuite CRM.png",

    // AWS extended
    "aws aurora postgresql": "AWS Aurora PostgreSQL.png",

    // IBM extended
    "ibm watson ml": "IBM Watson ML.png",

    // Infrastructure misc
    "infrastructure vendors": "Infrastructure Vendors.png",
    "scale computing platform": "Scale Computing Platform.png",
    "scale computing": "Scale Computing Platform.png",

    // SAP
    "sap": "SAP.webp",

    // Microsoft misc
    "microsoft": "microsoft.png",

    // Cisco extended
    "cisco intersight": "Cisco Intersight.png",
    "cisco meraki systems manager": "Cisco Meraki Systems Manager.png",
    "cisco meraki": "Cisco Meraki Systems Manager.png",
    // OEMs
    "oem": "OEMs.png",
    "oems": "OEMs.png",
    "oem vendors": "OEMs.png",
    // Newly added single-file and utility logos
    "backup & data protection vendor": "Backup & Data Protection Vendor.png",
    "infrastructure vendor": "Infrastructure Vendor.png",
    "os": "OS.png",
    "telecom carriers": "Telecom Carriers.svg",
    "telecom carrier": "Telecom Carriers.svg",
    "uem / mdm platforms": "UEM  MDM Platforms.png",
    "uem mdm platforms": "UEM  MDM Platforms.png",
  };
  
  // Try exact match first
  if (logoMap[normalized]) {
    const logoFile = logoMap[normalized];
    if (logoFile === null) {
      return null;
    }
    const logoFileLower = logoFile.toLowerCase();
    if (logoPathMap[logoFileLower]) {
      return logoPathMap[logoFileLower];
    } else {
    }
  }
  
  // Try partial matches - check if any key is contained in the normalized text
  const sortedKeys = Object.keys(logoMap).sort((a, b) => b.length - a.length);
  
  for (const key of sortedKeys) {
    if (normalized.includes(key) && key.length > 3) {
      const logoFile = logoMap[key];
      if (logoFile === null) continue;
      const logoFileLower = logoFile.toLowerCase();
      if (logoPathMap[logoFileLower]) {
        return logoPathMap[logoFileLower];
      }
    }
  }
  
  return null;
};

// Get colored React icon for technologies without logos
export const getTechIcon = (techName) => {
  if (!techName) return null;
  
  const normalized = techName.toLowerCase().trim();
  
  const faIcons = {
    "cloud": { component: FaCloud, color: "#4A90E2" },
    "cloud computing": { component: FaCloud, color: "#4A90E2" },
    "on prem": { component: FaDatabase, color: "#7ED321" },
    "on-prem": { component: FaDatabase, color: "#7ED321" },
    "not detected": { component: FaQuestionCircle, color: "#999999" },
  };
  
  const siIcons = {
    "azure": { name: "SiMicrosoftazure", color: "#0078D4" },
    "microsoft azure": { name: "SiMicrosoftazure", color: "#0078D4" },
    "azure sql": { name: "SiMicrosoftazure", color: "#0078D4" },
    "gemini": { name: "SiGoogle", color: "#4285F4" },
    "claude": { name: "SiAnthropic", color: "#000000" },
    "copilot": { name: "SiMicrosoft", color: "#00A4EF" },
    "mlflow": { name: "SiApache", color: "#13C127" },
    "hubspot": { name: "SiHubspot", color: "#FF7A59" },
    "zoho": { name: "SiZoho", color: "#1F73E7" },
    "pipedrive": { name: "SiPipedrive", color: "#1FD15F" },
    "dynamics crm": { name: "SiMicrosoftazure", color: "#0078D4" },
    "redis": { name: "SiRedis", color: "#DC382D" },
    "snowflake": { name: "SiSnowflake", color: "#29B5E8" },
    "ms sql": { name: "SiMicrosoftazure", color: "#0078D4" },
    "sql server": { name: "SiMicrosoftazure", color: "#0078D4" },
    "digitalocean": { name: "SiDigitalocean", color: "#0080FF" },
    "vmware": { name: "SiVmware", color: "#231F20" },
    "alibaba cloud": { name: "SiAlibaba", color: "#FF6A00" },
    "adobe": { name: "SiAdobe", color: "#FF0000" },
    "tableau": { name: "SiTableau", color: "#E97627" },
    "sap": { name: "SiSap", color: "#0CCEF7" },
    "docker": { name: "SiDocker", color: "#2496ED" },
    "kubernetes": { name: "SiKubernetes", color: "#326CE5" },
    "jenkins": { name: "SiJenkins", color: "#D33C27" },
    "git": { name: "SiGit", color: "#F1502F" },
    "github": { name: "SiGithub", color: "#181717" },
    "gitlab": { name: "SiGitlab", color: "#FCA121" },
    "python": { name: "SiPython", color: "#3776AB" },
    "java": { name: "SiJava", color: "#007396" },
    "javascript": { name: "SiJavascript", color: "#F7DF1E" },
    "react": { name: "SiReact", color: "#61DAFB" },
    "nodejs": { name: "SiNodedotjs", color: "#339933" },
    "elasticsearch": { name: "SiElasticsearch", color: "#005571" },
    "kafka": { name: "SiApachekafka", color: "#231F20" },
    "spark": { name: "SiApachespark", color: "#E25A1C" },
    "hadoop": { name: "SiApachehadoop", color: "#66CCFF" },
    "tensorflow": { name: "SiTensorflow", color: "#FF6F00" },
    "linux": { name: "SiLinux", color: "#FCC624" },
    "windows": { name: "SiWindows", color: "#0078D4" },
    "macos": { name: "SiApple", color: "#000000" },
    "ios": { name: "SiApple", color: "#000000" },
    "android": { name: "SiAndroid", color: "#3DDC84" },
    "nginx": { name: "SiNginx", color: "#009639" },
    "apache": { name: "SiApache", color: "#D70015" },
    "mailchimp": { name: "SiMailchimp", color: "#FFE01B" },
  };
  
  if (faIcons[normalized]) {
    const { component: IconComponent, color } = faIcons[normalized];
    return { component: IconComponent, color };
  }
  
  for (const [key, iconData] of Object.entries(faIcons)) {
    if ((normalized.includes(key) || key.includes(normalized)) && key.length > 2) {
      return { component: iconData.component, color: iconData.color };
    }
  }
  
  const siIconData = siIcons[normalized];
  if (siIconData) {
    const IconComponent = SiIcons[siIconData.name];
    if (IconComponent) {
      return { component: IconComponent, color: siIconData.color };
    } else {
    }
  }
  
  for (const [key, iconData] of Object.entries(siIcons)) {
    if ((normalized.includes(key) || key.includes(normalized)) && key.length > 2) {
      const IconComponent = SiIcons[iconData.name];
      if (IconComponent) {
        return { component: IconComponent, color: iconData.color };
      }
    }
  }
  
  return null;
};
