import * as SiIcons from 'react-icons/si';
import { FaCloud, FaDatabase, FaRobot, FaQuestionCircle } from 'react-icons/fa';

// Logo mapping - only for technologies that have actual logo images
export const getLogoPath = (techName) => {
  if (!techName) return null;
  
  const normalized = techName.toLowerCase().trim();
  
  // Only include technologies that have actual logo files
  const logoMap = {
    // Cloud Providers - AWS
    "aws": "aws.png",
    "amazon aws": "aws.png",
    "amazon": "amazon_web_services.png",
    "amazon web services": "amazon_web_services.png",
    "dynamodb": "amazon_dynamodb.png",
    "amazon dynamodb": "amazon_dynamodb.png",
    "amazon dynamodbAmazon Dynamodb": "amazon_dynamodb.png",
    "aws dynamodb": "aws_dynamodb.png",
    "aws rds": "aws_rds.png",
    "amazon rds": "amazon_rds.png",
    "amazon relational database service (rds)": "amazon_rds.png",
    "amazon aurora": "amazon_aurora.png",
    "aurora serverless": "aurora_serverless.png",
    "amazon q": "amazon_q.png",
    "amazon redshift": "amazon_redshift.png",
    "amazon s3": "amazon_s3.png",
    "amazon ec2": "amazon_ec2.png",
    "amazon ecs": "amazon_ecs.png",
    "amazon efs": "amazon_efs.png",
    "amazon cloudfront": "amazon_cloudfront.png",
    "amazon bedrock": "amazon_bedrock.png",
    "aws sagemaker": "aws_sagemaker.png",
    "aws govcloud": "aws_govcloud.png",
    "rds": "amazon_rds.png",
    "aws | cloud computing": "aws.png",
    
    // Microsoft Azure & Services
    "azure": "azure.png",
    "microsoft azure": "microsoft_azure.png",
    "azure sql": "azure_sql.png",
    "azure sql database": "azure_sql_database.png",
    "azure cosmos db": "azure_cosmos_db.png",
    "cosmos db": "cosmos_db.png",
    "azure databricks": "Microsoft.png",
    "azure openai": "azure_openai.png",
    "azure functions": "azure_functions.png",
    "azure app service": "azure_app_service.png",
    "azure blob storage": "azure_blob_storage.png",
    "azure kubernetes service": "azure_kubernetes_service.png",
    "aks": "aks.png",
    "azure devops": "azure_devops.png",
    "azure government": "azure_government.png",
    "azure ml": "Microsoft.png",
    "sql azure": "azure_sql.png",
    "copilot": "copilot_ai.png",
    "microsoft copilot": "microsoft_copilot.png",
    "github copilot": "github_copilot.png",
    "microsoft": "Microsoft.png",
    "microsoft dynamics crm": "dynamics_crm.png",
    "microsoft dynamics 365": "dynamics_365.png",
    "microsoft dynamics 365 crm": "dynamics_365_sales.png",
    "dynamics crm": "dynamics_crm.png",
    "dynamics 365": "dynamics_365.png",
    "ms sql": "ms_sql.png",
    "mssql": "mssql.png",
    "sql server": "sql_server.png",
    "t-sql": "t-sql.png",
    "t_sql": "t_sql.png",
    
    // GCP
    "gcp": "gcp.png",
    "google cloud platform": "google_cloud_platform.png",
    "google cloud": "google_cloud.png",
    "google cloud sql": "google_cloud_sql.png",
    "cloud sql": "cloud_sql.png",
    "google cloud spanner": "Google Cloud Spanner.jpg",
    "google firestore": "firestore.png",
    "firestore": "firestore.png",
    "google kubernetes engine": "google_kubernetes_engine.png",
    "gke": "gke.png",
    "google app engine": "google_app_engine.png",
    "google cloud storage": "google_cloud_storage.png",
    "google gemini": "google_gemini.png",
    "gemini": "gemini.png",
    "google": "Google.png",
    
    // AI Models (specific branded ones only)
    "openai": "openai.png",
    "openai api": "openai_api.png",
    "chatgpt": "chatgpt.png",
    "gpt-4": "gpt_4.png",
    "gpt-5": "gpt_5.png",
    "meta ai": "meta_ai.png",
    "perplexity ai": "perplexity_ai.png",
    "reka core": "reka_core.png",
    "lamini ai": "leena_ai.png",
    "leena ai": "leena_ai.png",
    "notion ai": "notion_ai.png",
    "pytorch": "pytorch.png",
    "tensorflow": "tensorflow.png",
    "keras": "keras.png",
    "jax": "jax.png",
    "mxnet": "mxnet.png",
    "scikit-learn": "scikit-learn.png",
    "scikit_learn": "scikit_learn.png",
    "xgboost": "xgboost.png",
    "anthropic": "anthropic.png",
    "claude": "claude.png",
    "claude 3": "claude_3.png",
    "cohere": "cohere.png",
    "mistral": "mistral.png",
    "deepseek": "deepseek.png",
    "deepseek r1": "deepseek_r1.png",
    "grok": "grok.png",
    "h2o ai": "h2o_ai.png",
    "hugging face": "hugging_face.png",
    "llama": "llama.png",
    "llamaindex": "llamaindex.png",
    "langchain": "langchain.png",
    "replicate": "replicate.png",
    "jasper ai": "jasper_ai.png",
    "midjourney": "midjourney.png",
    "dall-e": "dall_e.png",
    "imagen": "imagen.png",
    "stable diffusion": "stable_diffusion.png",
    "alphafold": "alphafold.png",
    "bert": "bert.png",
    "roberta": "roberta.png",
    "falcon": "falcon.png",
    "onnx": "onnx.png",
    "mlflow": "mlflow.png",
    "prefect": "prefect.png",
    "airflow": "airflow.png",
    "datarobot": "datarobot.png",
    "watsonx": "watsonx.png",
    "ibm watson": "ibm_watson.png",
    "chroma": "chroma.png",
    "milvus": "milvus.png",
    "pinecone": "pinecone.png",
    "weaviate": "weaviate.png",
    
    // CRM
    "crm": "crm.png",
    "crisp": "crisp.png",
    "salesforce": "salesforce.png",
    "salesforce crm": "salesforce_crm_software.png",
    "salesforce.com": "salesforce.png",
    "salesforce.": "salesforce.png",
    "salesforce sales cloud": "salesforce_service_cloud.png",
    "salesforce service cloud": "salesforce_service_cloud.png",
    "salesforce marketing cloud": "salesforce_marketing_cloud.png",
    "salesforce platform": "salesforce_platform.png",
    "salesforce einstein": "salesforce_einstein.png",
    "salesforce cpq": "salesforce.png",
    "salesforce lightning": "salesforce.png",
    "salesforce crmSalesforce": "salesforce.png",
    "salesforce partner": "salesforce.png",
    "pipedrive": "Pipedrive.png",
    "boost crm": "Boost CRM.png",
    "sugar crm": "Sugar CRM.webp",
    "sugarcrm": "sugarcrm.png",
    "veeva crm": "Veeva CRM.png",
    "veevcrm": "Veeva CRM.png",
    "peoplesoft crm": "PeopleSoft CRM.png",
    "oracle crm": "oracle_cx.png",
    "oracle ebs crm": "oracle_cx.png",
    "oracle cx": "oracle_cx.png",
    "siebel": "oracle_cx.png",
    "sap crm": "sap_crm.png",
    "sap sales cloud": "sap_sales_cloud.png",
    "sap r3 crm": "sap_crm.png",
    "omni-channel crm": "customer_engagement_platform.png",
    "on-premise crm": "on-premise_crm.png",
    "hubspot": "hubspot.png",
    "hubspot crm": "hubspot.png",
    "hubsot crm": "hubspot.png",
    "zoho": "zoho.png",
    "zoho crm": "zoho_crm.png",
    "zoho desk": "zoho_desk.png",
    "netsuite crm": "netsuite_crm.png",
    "servicenow": "servicenow.png",
    "agile crm": "Agile CRM.jpg",
    "bitrix24": "Bitrix24.png",
    "copper": "Copper.png",
    "creatio": "Creatio.png",
    "crmnext": "crmnext.png",
    "freshsales": "FreshSales.png",
    "insightly": "insightly.png",
    "leadsquared": "leadsquared.png",
    "mailchimp": "MailChimp.png",
    "intuit mailchimp": "MailChimp.png",
    "monday sales crm": "Monday Sales CRM.png",
    "nimble crm": "Nimble CRM.png",
    "sage crm": "sage_crm.png",
    "sprinklr": "sprinklr.png",
    "zendesk sell": "Zendesk Sell.png",
    
    // Databases
    "mongodb": "mongodb.png",
    "mongo db": "mongo_db.png",
    "mongodb atlas": "mongodb_atlas.png",
    "mongodbMongodb": "mongodb.png",
    "mysql": "mysql.png",
    "mysql database": "mysql.png",
    "mysql server": "mysql_server.png",
    "mysql cluster": "mysql_cluster.png",
    "mysq": "mysql.png",
    "innodb": "innodb.png",
    "mariadb": "mariadb.png",
    "postgresql": "postgresql.png",
    "postgre sql": "postgresql.png",
    "postgres": "postgresql.png",
    "postgres db": "postgres_db.png",
    "postgis": "postgis.png",
    "oracle database": "oracle_database.png",
    "oracle sql": "oracle_database.png",
    "oracle cloud": "oracle_cloud.png",
    "oracle cloud infrastructure": "oracle_cloud_infrastructure.png",
    "oracle autonomous database": "oracle_autonomous_database.png",
    "oracle exadata": "oracle_exadata.png",
    "oracle 11g": "oracle_11g.png",
    "oracle 12c": "oracle_12c.png",
    "oracle db": "oracle_db.png",
    "oracle": "Oracle.png",
    "oracle database administration": "oracle_database.png",
    "ibm db2": "ibm_db2.png",
    "ibm db2": "IBM DB2.png",
    "db2 database": "db2_database.png",
    "hive": "apache_hive.png",
    "apache hive": "apache_hive.png",
    "firebase": "firebase.png",
    "amazon documentdb": "amazon_documentdb.png",
    "snowflake": "snowflake.png",
    "snowflake cloud": "snowflake_data_cloud.png",
    "snowflakecloud": "snowflake_data_cloud.png",
    "snowflake warehouse": "snowflake_warehouse.png",
    "snowflake on aws": "snowflake_on_aws.png",
    "redis": "redis.png",
    "redis cache": "redis_cache.png",
    "redis cluster": "redis_cluster.png",
    "elasticsearch": "elasticsearch.png",
    "kafka": "kafka.png",
    "spark": "spark.png",
    "hadoop": "hadoop.png",
    "teradata": "teradata.png",
    "teradata vantage": "teradata_vantage.png",
    "timescaledb": "timescaledb.png",
    "marklogic": "marklogic.png",
    "mark logic": "Mark Logic.png",
    "enterprisedb": "enterprisedb.png",
    "bigquery": "bigquery.png",
    "big data sql": "big_data_sql.png",
    "cloud data warehouse": "cloud_data_warehouse.png",
    "enterprise data warehouse": "enterprise_data_warehouse.png",
    "document database": "document_database.png",
    "multi model database": "multi_model_database.png",
    "nosql database": "nosql_database.png",
    
    // Cloud Services
    "ibm cloud": "ibm_cloud.png",
    "ibm bluemix": "ibm_bluemix.png",
    "lumen cloud": "Rackspace Cloud.jpg",
    "rackspace cloud": "Rackspace Cloud.jpg",
    "sciex cloud": "Sciex Cloud.png",
    "alibaba cloud": "Alibaba Cloud.png",
    "digitalocean": "digitalocean.png",
    "linode": "linode.png",
    "vultr": "vultr.png",
    "heroku": "heroku.png",
    "coreweave": "coreweave.png",
    "vmware": "vmware.png",
    "vmware cloud": "vmware_cloud.png",
    "vmware vsphere": "vmware_vsphere.png",
    "nutanix": "nutanix.png",
    "openstack": "openstack.png",
    "openshift": "openshift.png",
    "red hat openshift": "red hat openshift.svg",
    "oci": "oci.png",
    "oracle cloud infrastructure": "oracle_cloud_infrastructure.png",
    
    // AI/ML Concepts
    "ai": "ai.png",
    "artificial intelligence": "artificial_intelligence.png",
    "artificial intellige": "artificial_intelligence.png",
    "artificial intelligen": "artificial_intelligence.png",
    "machine learning": "machine_learning.png",
    "machine learningmachnine learning": "machine_learning.png",
    "machine learn": "machine_learning.png",
    "deep learning": "deep_learning.png",
    "nlp": "nlp.png",
    "natural language processing": "natural_language_processing.png",
    "computer vision": "computer_vision.png",
    "gen ai": "generative_ai.png",
    "genai": "generative_ai.png",
    "llm": "LLM.png",
    "large language model": "Large Language Model.png",
    "foundation models": "foundation_models.png",
    "embeddings": "embeddings.png",
    "rag": "rag.png",
    "fine-tuning": "fine-tuning.png",
    "fine_tuning": "fine_tuning.png",
    "prompt engineering": "prompt_engineering.png",
    "model training": "model_training.png",
    "neural networks": "neural_networks.png",
    "neural network": "Neural Network.png",
    "transformers": "transformers.png",
    "anomaly detection": "anomaly_detection.png",
    "fraud detection": "fraud_detection.png",
    "sentiment analysis": "sentiment_analysis.png",
    "recommendation engine": "recommendation_engine.png",
    "predictive analytics": "predictive_analytics.png",
    "reinforcement learning": "reinforcement_learning.png",
    "image generation": "image_generation.png",
    "text to speech": "text_to_speech.png",
    "speech recognition": "speech_recognition.png",
    "search": "search.png",
    "enterprise ai": "enterprise_ai.png",
    "ai/ml": "aiml.png",
    "aiml": "aiml.png",
    
    // Infrastructure & DevOps
    "docker": "docker.png",
    "kubernetes": "kubernetes.png",
    "jenkins": "jenkins.png",
    "git": "git.png",
    "github": "github.png",
    "gitlab": "gitlab.png",
    "nginx": "nginx.png",
    "apache": "apache.png",
    "tomcat": "tomcat.png",
    "linux": "linux.png",
    "windows": "windows.png",
    "macos": "macos.png",
    "ios": "ios.png",
    "android": "android.png",
    "python": "python.png",
    "java": "java.png",
    "javascript": "javascript.png",
    "react": "react.png",
    "nodejs": "nodejs.png",
    "node.js": "nodejs.png",
    
    // Cloud Platforms & Services
    "cloudflare": "cloudflare.png",
    "cloudflare workers": "cloudflare_workers.png",
    "akamai": "akamai.png",
    "edge computing": "edge_computing.png",
    "gpu cloud": "gpu_cloud.png",
    "app platform": "app_platform.png",
    "managed databases": "managed_databases.png",
    "managed rds": "managed_rds.png",
    "virtual private cloud": "virtual_private_cloud.png",
    "government cloud": "government_cloud.png",
    "fedramp": "fedramp.png",
    "itar compliance": "itar_compliance.png",
    
    // Generic/Fallback
    "on prem": "database.png",
    "on-prem": "database.png",
    "not detected": null,
    "not detectedNot detected": null,
    "database": "database.png",
    "cloud": "cloud.png",
    "cloud computing": "cloud_computing.png",
    "ai cloud platform": "ai_cloud_platform.png",
    "ai infrastructure": "ai_infrastructure.png",
    "ai orchestration": "ai_orchestration.png",
  };
  
  // Try exact match first
  if (logoMap[normalized]) {
    return `/src/logos/${logoMap[normalized]}`;
  }
  
  // Try partial matches - check if any key is contained in the normalized text
  // Sort by key length (longest first) to match more specific terms first
  const sortedKeys = Object.keys(logoMap).sort((a, b) => b.length - a.length);
  
  for (const key of sortedKeys) {
    // Skip very short keys to avoid false matches (e.g., "ai" matching "generative ai")
    if (normalized.includes(key) && key.length > 3) {
      return `/src/logos/${logoMap[key]}`;
    }
  }
  
  // Return null if no logo found - will use icon instead
  return null;
};

// Get colored React icon for technologies without logos
export const getTechIcon = (techName) => {
  if (!techName) return null;
  
  const normalized = techName.toLowerCase().trim();
  
  // FA icons mapping
  const faIcons = {
    "ai": { component: FaRobot, color: "#8B5CF6", strokeWidth: 1.5 },
    "ai/ml": { component: FaRobot, color: "#8B5CF6", strokeWidth: 1.5 },
    "aiml": { component: FaRobot, color: "#8B5CF6", strokeWidth: 1.5 },
    "artificial intelligence": { component: FaRobot, color: "#8B5CF6", strokeWidth: 1.5 },
    "artificial intelligence (ai)": { component: FaRobot, color: "#8B5CF6", strokeWidth: 1.5 },
    "artificial intellige": { component: FaRobot, color: "#8B5CF6", strokeWidth: 1.5 },
    "artificial intelligen": { component: FaRobot, color: "#8B5CF6", strokeWidth: 1.5 },
    "machine learning": { component: FaRobot, color: "#8B5CF6", strokeWidth: 1.5 },
    "machine learningmachnine learning": { component: FaRobot, color: "#8B5CF6", strokeWidth: 1.5 },
    "machine learn": { component: FaRobot, color: "#8B5CF6", strokeWidth: 1.5 },
    "deep learning": { component: FaRobot, color: "#8B5CF6", strokeWidth: 1.5 },
    "nlp": { component: FaRobot, color: "#8B5CF6", strokeWidth: 1.5 },
    "natural language processing": { component: FaRobot, color: "#8B5CF6", strokeWidth: 1.5 },
    "computer vision": { component: FaRobot, color: "#8B5CF6", strokeWidth: 1.5 },
    "gen ai": { component: FaRobot, color: "#8B5CF6", strokeWidth: 1.5 },
    "genai": { component: FaRobot, color: "#8B5CF6", strokeWidth: 1.5 },
    "generative ai": { component: FaRobot, color: "#8B5CF6", strokeWidth: 1.5 },
    "llm": { component: FaRobot, color: "#8B5CF6", strokeWidth: 1.5 },
    "pytorch": { component: FaRobot, color: "#8B5CF6", strokeWidth: 1.5 },
    "cloud": { component: FaCloud, color: "#4A90E2" },
    "cloud | aws": { component: FaCloud, color: "#4A90E2" },
    "cloud computing": { component: FaCloud, color: "#4A90E2" },
    "hive": { component: FaDatabase, color: "#F5A623" },
    "on prem": { component: FaDatabase, color: "#7ED321" },
    "on-prem": { component: FaDatabase, color: "#7ED321" },
    "not detected": { component: FaQuestionCircle, color: "#999999" },
    "not detectedNot detected": { component: FaQuestionCircle, color: "#999999" },
  };
  
  // SI icons mapping with colors
  const siIcons = {
    "azure": { name: "SiMicrosoftazure", color: "#0078D4" },
    "microsoft azure": { name: "SiMicrosoftazure", color: "#0078D4" },
    "azure sql": { name: "SiMicrosoftazure", color: "#0078D4" },
    "azure sql database": { name: "SiMicrosoftazure", color: "#0078D4" },
    "azure cosmos db": { name: "SiMicrosoftazure", color: "#0078D4" },
    "azure databricks": { name: "SiMicrosoftazure", color: "#0078D4" },
    "azure openai": { name: "SiMicrosoftazure", color: "#0078D4" },
    "sql azure": { name: "SiMicrosoftazure", color: "#0078D4" },
    "gemini": { name: "SiGoogle", color: "#4285F4" },
    "claude": { name: "SiAnthropic", color: "#000000" },
    "copilot": { name: "SiMicrosoft", color: "#00A4EF" },
    "mlflow": { name: "SiApache", color: "#13C127" },
    "hubspot": { name: "SiHubspot", color: "#FF7A59" },
    "hubspot crm": { name: "SiHubspot", color: "#FF7A59" },
    "hubsot crm": { name: "SiHubspot", color: "#FF7A59" },
    "zoho": { name: "SiZoho", color: "#1F73E7" },
    "zoho crm": { name: "SiZoho", color: "#1F73E7" },
    "pipedrive": { name: "SiPipedrive", color: "#1FD15F" },
    "dynamics crm": { name: "SiMicrosoftazure", color: "#0078D4" },
    "microsoft dynamics crm": { name: "SiMicrosoftazure", color: "#0078D4" },
    "microsoft dynamics 365": { name: "SiMicrosoftazure", color: "#0078D4" },
    "microsoft dynamics 365 crm": { name: "SiMicrosoftazure", color: "#0078D4" },
    "redis": { name: "SiRedis", color: "#DC382D" },
    "snowflake": { name: "SiSnowflake", color: "#29B5E8" },
    "snowflake cloud": { name: "SiSnowflake", color: "#29B5E8" },
    "snowflakecloud": { name: "SiSnowflake", color: "#29B5E8" },
    "ms sql": { name: "SiMicrosoftazure", color: "#0078D4" },
    "sql server": { name: "SiMicrosoftazure", color: "#0078D4" },
    "digitalocean": { name: "SiDigitalocean", color: "#0080FF" },
    "vmware": { name: "SiVmware", color: "#231F20" },
    "vmware | aws | google cloud platform": { name: "SiVmware", color: "#231F20" },
    "alibaba cloud": { name: "SiAlibaba", color: "#FF6A00" },
    "adobe": { name: "SiAdobe", color: "#FF0000" },
    "adobe experience cloud": { name: "SiAdobe", color: "#FF0000" },
    "tableau": { name: "SiTableau", color: "#E97627" },
    "tableau crm": { name: "SiTableau", color: "#E97627" },
    "sap analytics cloud": { name: "SiSap", color: "#0CCEF7" },
    "sap": { name: "SiSap", color: "#0CCEF7" },
    "sap crmsciex cloud": { name: "SiSap", color: "#0CCEF7" },
    "docker": { name: "SiDocker", color: "#2496ED" },
    "kubernetes": { name: "SiKubernetes", color: "#326CE5" },
    "jenkins": { name: "SiJenkins", color: "#D33C27" },
    "git": { name: "SiGit", color: "#F1502F" },
    "github": { name: "SiGithub", color: "#181717" },
    "gitlab": { name: "SiGitlab", color: "#FCA121" },
    "python": { name: "SiPython", color: "#3776AB" },
    "java": { name: "SiJava", color: "#007396" },
    "javascript": { name: "SiJavascript", color: "#F7DF1E" },
    "react": { name: "SiReact", color: "#61DAFB" },
    "nodejs": { name: "SiNodedotjs", color: "#339933" },
    "node.js": { name: "SiNodedotjs", color: "#339933" },
    "elasticsearch": { name: "SiElasticsearch", color: "#005571" },
    "kafka": { name: "SiApachekafka", color: "#231F20" },
    "spark": { name: "SiApachespark", color: "#E25A1C" },
    "hadoop": { name: "SiApachehadoop", color: "#66CCFF" },
    "tensorflow": { name: "SiTensorflow", color: "#FF6F00" },
    "linux": { name: "SiLinux", color: "#FCC624" },
    "windows": { name: "SiWindows", color: "#0078D4" },
    "macos": { name: "SiApple", color: "#000000" },
    "ios": { name: "SiApple", color: "#000000" },
    "android": { name: "SiAndroid", color: "#3DDC84" },
    "nginx": { name: "SiNginx", color: "#009639" },
    "apache": { name: "SiApache", color: "#D70015" },
    "tomcat": { name: "SiApachetomcat", color: "#F8DC75" },
    // Additional CRM and services
    "mailchimp": { name: "SiMailchimp", color: "#FFE01B" },
    "intuit mailchimp": { name: "SiMailchimp", color: "#FFE01B" },
    "boost crm": { name: "SiMicrosoft", color: "#00A4EF" },
    "sugar crm": { name: "SiSalesforce", color: "#00A1E0" },
    "sugarcrm": { name: "SiSalesforce", color: "#00A1E0" },
    "veeva crm": { name: "SiSalesforce", color: "#00A1E0" },
    "peoplesoft crm": { name: "SiOracle", color: "#F80000" },
    "rackspace cloud": { name: "SiRackspace", color: "#C40022" },
    "lumen cloud": { name: "SiCenturylink", color: "#0066CC" },
    "sciex cloud": { name: "SiSap", color: "#0CCEF7" },
  };
  
  // Check FA icons first
  if (faIcons[normalized]) {
    const { component: IconComponent, color } = faIcons[normalized];
    return { component: IconComponent, color };
  }
  
  // Check for partial matches in FA icons
  for (const [key, iconData] of Object.entries(faIcons)) {
    if ((normalized.includes(key) || key.includes(normalized)) && key.length > 2) {
      return { component: iconData.component, color: iconData.color };
    }
  }
  
  // Fallback: Check if it contains "artificial" or "machine" keywords
  if (normalized.includes("artificial") || normalized.includes("machine")) {
    return { component: FaRobot, color: "#8B5CF6" };
  }
  
  // Check SI icons
  const siIconData = siIcons[normalized];
  if (siIconData) {
    const IconComponent = SiIcons[siIconData.name];
    if (IconComponent) {
      return { component: IconComponent, color: siIconData.color };
    }
  }
  
  // Check for partial matches in SI icons
  for (const [key, iconData] of Object.entries(siIcons)) {
    if ((normalized.includes(key) || key.includes(normalized)) && key.length > 2) {
      const IconComponent = SiIcons[iconData.name];
      if (IconComponent) {
        return { component: IconComponent, color: iconData.color };
      }
    }
  }
  
  return null;
};
